Lesson 2
EkaterinaPoddubskaya/lesson-1 pull request #3
Opened 2024-08-07 15:11 UTC by EkaterinaPoddubskaya

Lesson 2 task completed.
User interaction was added via:
1) a popup on “Profile” button click
2) a working form allowing to:  
                                                  - add films to the datatable, 
                                                  - check if form data is valid,
                                                  - show a message if validation is successful,
                                                  - show the warning text for fields where data is invalid,
                                                  - clear form fields after user confirmation.

2024-08-08 09:52 UTC, VeraOrekhXB requested changes

2024-08-08 09:52 UTC, VeraOrekhXB commented on main.js
> +            id: "myprofile",
No `my` in the ids. It would be better to rename it to smth like `profileButton`/`profileBtn`

2024-08-08 09:52 UTC, VeraOrekhXB commented on user-interaction.js
> +$$("myprofile").attachEvent("onItemClick", function() {
You may define popup in the button config
In this case it popup should automatically appear on button click
https://docs.webix.com/desktop__popup.html#creatingpopupmenu

2024-08-08 09:52 UTC, VeraOrekhXB commented on user-interaction.js
> +$$("myaddnew").attachEvent("onItemClick", function() {
It's more preferable to use arrow functions

2024-08-08 09:52 UTC, VeraOrekhXB commented on user-interaction.js
> +const titleInput = $$("myform").elements.title;
It'd be better to define a separate variable for a form

2024-08-08 09:52 UTC, VeraOrekhXB commented on user-interaction.js
> +        const film = {
You may use `form.getValues()` method
https://docs.webix.com/api__link__ui.form_getvalues.html

2024-08-08 09:52 UTC, VeraOrekhXB commented on user-interaction.js
> +            titleInput.setValue("");
Use [`clear`](https://docs.webix.com/api__link__ui.form_clear.html) method

2024-08-08 09:52 UTC, VeraOrekhXB commented on user-interaction.js
> +$$("myclear").attachEvent("onItemClick", function() {
To prevent memory leaks don't forget to detach events
A quick fix for you right now you may define events inside the config using [`click`](https://docs.webix.com/api__ui.button_click_config.html)

2024-08-08 09:52 UTC, VeraOrekhXB commented on main.js
> +    rules:{
- Do not save spaces in the beginning/end of the sting
- Prevent XSS injections
- On save convert data to the proper format. For example, year should be a number, not a string
- Validate a value format. A film rating has to be a number

![image](https://github.com/user-attachments/assets/d3dcc145-c47a-4ab3-bdf9-9bdf24b2abc5)

2024-08-08 09:52 UTC, VeraOrekhXB commented on user-interaction.js
> +        $$('mytable').add(film);
After values saving, form has to be cleared

2024-08-08 09:52 UTC, VeraOrekhXB commented on main.js
> +            { view:"text", label:"Year", name: "year", value:"", invalidMessage: "Enter year between 1970 and " + new Date().getFullYear() },
Use `es6` template strings

2024-08-09 13:47 UTC, VeraOrekhXB requested changes

2024-08-09 13:47 UTC, VeraOrekhXB commented on main.js
> +            return Number.isInteger(value) && (value >= 1970) && (value <= new Date().getFullYear());
`value` is a string, that's why `Number.isInteger(value)` will always return false

2024-08-12 15:19 UTC, VeraOrekhXB requested changes

2024-08-12 15:19 UTC, VeraOrekhXB commented on main.js
> +                        return NaN;
You may shorten it to `return value || null`

2024-08-12 15:19 UTC, VeraOrekhXB commented on main.js
> +                        if (value > 9999) {
In your case it's necessary just to convert the value to number or `null`, the validation will be done in the `validate`

2024-08-12 15:19 UTC, VeraOrekhXB commented on main.js
> +                invalidMessage: "",
You may skip it if there is no default value for invalid message

2024-08-12 15:19 UTC, VeraOrekhXB commented on main.js
> +                    let invMessage = "Rating can not be empty";
In this case I'd not shorten `invalid` word, it's hard to understand the initial word
Instead, you may shorten `message` (`invalidMsg`) or use full words (`invalidMessage`)

2024-08-12 15:19 UTC, VeraOrekhXB commented on main.js
> +                            return true;
In most of the cases it's better to have just one `return` in the end of the function
In your case you may return `true` or `false` depending on  if there is invalid message or not

2024-08-12 15:19 UTC, VeraOrekhXB commented on main.js
> +           'onTimedKeyPress'() {
You may remove `'`

2024-08-12 15:19 UTC, VeraOrekhXB commented on main.js
> +                        invMessage = `Enter year between 1970 and ${new Date().getFullYear()}`;
The current year value is calculated twice: once for condition, and the second time for error message
Please, calculate it once
Also it's better to put start year `1970` inside the variable and the use it
As in the future if it's necessary to change it, there is less code to change and check
+ there is less chance that in the check and in the error message there are different values

2024-08-12 16:11 UTC, EkaterinaPoddubskaya commented on main.js
> +                        return NaN;
Form doesn't work with null though, that's why I used NaN

2024-08-12 16:50 UTC, VeraOrekhXB requested changes

2024-08-12 16:50 UTC, VeraOrekhXB commented on main.js
> +                    let noInvalidMessage = false;
There is no need in the flag, you may use `invalidMessage` value
The initial value is empty and if there's smth wrong, define the message
And on return check if `invalidMessage` is empty or not

2024-08-12 16:50 UTC, VeraOrekhXB commented on main.js
> +                    return  noInvalidMessage;
`validate` functions for year & rating & votes are similar
You may define one function and provide min/max values & view in parameters

2024-08-13 10:45 UTC, VeraOrekhXB requested changes

2024-08-13 10:45 UTC, VeraOrekhXB commented on scripts/validation.js
> +    else return true;
Simplify to `return !!invalidMessage`

2024-08-13 10:45 UTC, VeraOrekhXB commented on scripts/validation.js
> +        if (webix.rules.isNumber(value)) {
There is no need to have a separate check for rating and other fields
`webix.rules.isNumber(value)` is enough for all cases
If you want to have separate checks for float & integer values, it's better to provide a type for check in function parameters, not view id
In this case if id will be changed or there're more new similar fields in the form, the validate function could be easily reused

2024-08-13 10:45 UTC, VeraOrekhXB commented on scripts/validation.js
> +validateFormElements = (value, minValue, maxValue, invalidMes1, invalidMes2, view) => {
It's not a good practice to name variables like value1, value2, etc., there should be more information. For example, `invalidRangeMsg`, `invalidValueTypeMsg`
Also in your case you may define a common error message: `Enter a value between ${minValue} and ${maxValue}`

2024-08-13 13:34 UTC, merged